Flatbuffers
jcarreira/cirrus pull request #65
Opened 2018-07-19 07:06 UTC by neelsomani

**Not ready to merge.**

First few commits for FlatBuffers implementation to get preliminary feedback (before replacing the rest of the serialization calls).

* Added flatc installation and .fbs file generation
* Replaced the serialization for *only* `SEND_LR_GRADIENT` to get feedback

Based on the schema specified [here](https://docs.google.com/document/d/1H7bG98R3Zg33_8s47d39zR5C3ptBXNAaQNDUyqTXpoA/).

2018-07-19 07:07 UTC, neelsomani commented on src/PSSparseServerInterface.cpp
> +  flatbuffers::FlatBufferBuilder builder(1024);
Will change this so it uses `initial_buffer_size` above

2018-07-19 22:20 UTC, jcarreira requested changes

2018-07-19 22:20 UTC, jcarreira commented on src/PSSparseServerInterface.cpp
> +  auto grad_vec = builder.CreateUninitializedVector(grad_size, (unsigned char **) &buf);
We should use C++ casts.

2018-07-19 22:20 UTC, jcarreira commented on src/PSSparseServerInterface.cpp
> +  if (send(sock, &size, sizeof(int), 0) < 1) {
Here we should use send_all (we didn't use previously by mistake).

2018-07-19 22:20 UTC, jcarreira commented on src/PSSparseServerTask.cpp
> +            process_send_lr_gradient(&gradient_buf);
I don't think we need to pass a pointer to a pointer here.

2018-07-28 22:53 UTC, neelsomani commented
Hi @jcarreira, I've finished replacing the remaining serialization calls. Mind reviewing the latest changes? Thanks!

2018-07-28 23:43 UTC, jcarreira commented
It seems there is an issues with travis:

```
In file included from [01m[K./Tasks.h:9:0[m[K,
                 from [01m[Kparameter_server.cpp:2[m[K:
[01m[K./PSSparseServerInterface.h:19:48:[m[K [01;31m[Kfatal error: [m[Kcommon/schemas/PSMessage_generated.h: No such file or directory
 #include "common/schemas/PSMessage_generated.h"
```

Can you fix that first?

2018-08-09 21:53 UTC, neelsomani commented
**Not ready to merge.**

**TODO:**
1. Write (and pass) MF test
2. Benchmark

2018-08-29 22:08 UTC, neelsomani commented
*Ready to merge.*

With FlatBuffers:
MF test average events per second: 530.41
LR test average events per second: 4532

Without FlatBuffers:
MF test average events per second: 431.10
LR test average events per second: 4385

2018-08-31 16:28 UTC, jcarreira commented
We agreed during the Tuesday meetings that it would be better to donwload the datasets from S3 instead of putting them in the github.

2018-08-31 17:03 UTC, jcarreira commented
I suggest we create a new PR with the style changes.

2018-10-04 20:41 UTC, jcarreira commented
Please fix this conflict. After that I will do a few more tests so hopefully we can merge this soon.

2018-10-09 05:17 UTC, neelsomani commented
Hey @jcarreira, I merged master into this branch. The tests run successfully on the VM. Looks like the error on Travis is the same error that's happening master itself; it's not related to this PR. Ready for review here.

2018-10-16 21:33 UTC, jcarreira commented
Please fix conflicts.

2018-10-22 22:25 UTC, jcarreira requested changes

2018-10-24 20:08 UTC, jcarreira commented
Let's change the code to allocate/deallocate that memory (using smart pointers). It;s safer that way.

2026-07-09 04:24 UTC, closed without merging